samsonov-alexander-task-8
mak-42/ws2023spb-knightsmove pull request #2
Opened 2023-10-29 11:15 UTC by Mayonnaise-Slap

2023-10-30 14:11 UTC, mak-42 commented
Текст тестов тоже не должен изменяться (об этом предупреждали, когда выдавали задание). Пожалуйста, реализуй задание так, чтобы среди изменённых файлов не было тестов,

2023-10-30 15:11 UTC, mak-42 requested changes

2023-10-30 15:11 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/ChessPosition.java
> -public interface ChessPosition {
В этом задании некоторое количество кода уже было реализовано, чтобы дать представление о работе в команде. Если в реальном проекте договорились, что это будет интерфейс и несколько команд его используют, то такое изменение, сделанные одной из команд, парализует работу остальных. 
Верни, пожалуйста, интерфейс.

2023-10-31 09:43 UTC, Mayonnaise-Slap commented
1. Текст тестов автоматически рефакторит IDEA
2. Также она подчеркивает этот момент в комментариях
<img width="628" alt="image" src="https://github.com/mak-42/ws2023spb-knightsmove/assets/112976482/83645630-d5de-482e-8a29-96df32228e76">

Оно конечно собирается, но ide на все ругается.

остальное исправил и сейчас загружу

2023-10-31 09:54 UTC, Mayonnaise-Slap commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveCheckerFactory.java
> +import croc.education.ws2023spb.knightsmove.exceptions.IllegalMoveException;
Пожалуйста, посмотрите отмеченные изменения в тестах. Единственное рукотворное изменение - эта строчка, где я импортирую exception для его обработки. Конечно можно вынести их из папки в `src/main/java/croc/education/ws2023spb/knightsmove`, но так проект чуть чище. В остальных тестах он отмечает изменениями удаленные пробелы

2023-10-31 17:00 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveCheckerFactory.java
> +import croc.education.ws2023spb.knightsmove.exceptions.IllegalMoveException;
Согласно заданию текст тестов не должен изменяться. Пожалуйста, верните текст тестов в исходное состояние. Реализация должна полностью удовлетворять им без единого изменения. 

Как я уже писал выше, что некоторое количество кода было реализовано, чтобы дать представление о работе в команде. Считайте, что тесты - это использование вашей реализации другой командой. И такого кода может быть уже много. В такой ситуации изменения начальных договорённостей обычно дорого стоят и могут проводиться только в случае, если на это есть веская причина.

2023-10-31 18:46 UTC, Mayonnaise-Slap commented
Все тесты проходят, все пробелы на месте, все файлы лежат в одной папке
Будут правки к логике?

2023-11-04 08:49 UTC, mak-42 requested changes
Хорошая работа. Осталось поправить несколько проблем для зачёта на максимальный балл.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveChecker.java
> +public abstract class KnightsMoveChecker {
Пожалуйста, верни интерфейс и сделай отдельную реализацию, его имплементирующую. Здесь уже это обсуждали: https://github.com/mak-42/ws2023spb-knightsmove/pull/2#discussion_r1376283467
Много времени на это не должно понадобиться..

В pull request'е не должно быть изменений кода интерфейса.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/ChessPositionParser.java
> +        if (position.length() != 2) throw new IllegalPositionException("the position is formatted wrongly");
Исключение получилось довольно неинформативным: по сообщению не понятно, что за значение обрабатывалось. Если рассматривать решение целиком, это создаст неудобства его пользователю, т.к. в случае ошибки при вводе большой последовательности ходов, ему не будет понятно, что же конкретно он ввёл с ошибкой.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/IllegalPositionException.java
> +public class IllegalPositionException extends IndexOutOfBoundsException {
Выбрать для наследование более узкий тип исключения - отличное решение. Однако ```java.lang.IllegalArgumentException``` в качестве родительского класса подойдёт здесь лучше.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/ChessPositionParser.java
> +                return HorizontalChar - 'a';
В данном случае вычисления будут производиться при каждом вызове метода. Для геттеров - это считается плохой практикой. Измените. пожалуйста, код так, чтобы вычисление производилось единожды.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/ChessPosition.java
> + *
Спасибо, что убрали значимые изменения в интерфейсе. Однако остались не значимые. Это считается плохой практикой, т.к. для проверяющего код файл попадает в список изменённых, а смотреть там нечего.

2023-11-04 08:49 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveChecker.java
> +            if (deltaX + deltaY != legalDistance)
Сделать проверку по количеству пройденных клеток - отличное решение. Однако, если не ошибаюсь, оно получилось не полным: ход ```b1```-```b4``` будет считаться правильным, но это не так.

2023-11-04 10:58 UTC, mak-42 requested changes

2023-11-04 10:58 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveChecker.java
> +        for (var position : positions) {
При реализации можно обойтись без этого списка. Получается, что сначала вы проходитесь по массиву ходов, чтобы преобразовать его в список, а потом по списку, чтобы осуществить проверку. Можно сделать за один проход.

2023-11-13 06:39 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/KnightsMoveChecker.java
> +public abstract class KnightsMoveChecker {
Печально, что вы не вернули интерфейс к первоначальному виду :-(
![image](https://github.com/mak-42/ws2023spb-knightsmove/assets/17267223/e043a58e-6073-4cfe-bae7-786cffd9eec8)

2023-11-13 06:42 UTC, mak-42 commented on src/main/java/croc/education/ws2023spb/knightsmove/ChessPositionParser.java
> +        if (position.length() != 2) throw new IllegalPositionException("the position is formatted wrongly");
Печально, что поправили только здесь. Остались аналогичные проблемы в других местах :-(

```java
        if (HorizontalChar < 'a' || 'h' < HorizontalChar || VerticalChar < '1' || VerticalChar > '8') {
            throw new IllegalPositionException("The position is out of bounds");
        }
```

2023-11-13 06:46 UTC, mak-42 commented
Успеете поправить сегодня, зачту с этими исправлениями. Нет, зачту без них.

2023-12-26 14:27 UTC, closed without merging